In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date, datetime
import calendar
import holidays

In [4]:
df = pd.read_csv('../../datos/00-bikes.csv',index_col = 0)

In [3]:
df.head(2)

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  01-01-2018  spring   0     1        0        6           0   
1        2  02-01-2018  spring   0     1        0        0           0   

   weathersit       temp     atemp      hum  windspeed  casual  registered  \
0           2  14.110847  18.18125  80.5833  10.749882     331         654   
1           2  14.902598  17.68695  69.6087  16.652113     131         670   

   cnt  
0  985  
1  801

columnas numéricas

In [4]:
df.describe().T

count         mean          std        min          25%  \
instant     730.0   365.500000   210.877136   1.000000   183.250000   
yr          730.0     0.500000     0.500343   0.000000     0.000000   
mnth        730.0     6.526027     3.450215   1.000000     4.000000   
holiday     730.0     0.028767     0.167266   0.000000     0.000000   
weekday     730.0     2.997260     2.006161   0.000000     1.000000   
workingday  730.0     0.683562     0.465405   0.000000     0.000000   
weathersit  730.0     1.394521     0.544807   1.000000     1.000000   
temp        730.0    20.319259     7.506729   2.424346    13.811885   
atemp       730.0    23.726322     8.150308   3.953480    16.889713   
hum         730.0    62.765175    14.237589   0.000000    52.000000   
windspeed   730.0    12.763620     5.195841   1.500244     9.041650   
casual      730.0   849.249315   686.479875   2.000000   316.250000   
registered  730.0  3658.757534  1559.758728  20.000000  2502.250000   
cnt         730.0  4508.006849  1936.011647  22.000000  3169.750000   

                    50%          75%          max  
instant      365.500000   547.750000   730.000000  
yr             0.500000     1.000000     1.000000  
mnth           7.000000    10.000000    12.000000  
holiday        0.000000     0.000000     1.000000  
weekday        3.000000     5.000000     6.000000  
workingday     1.000000     1.000000     1.000000  
weathersit     1.000000     2.000000     3.000000  
temp          20.465826    26.880615    35.328347  
atemp         24.368225    30.445775    42.044800  
hum           62.625000    72.989575    97.250000  
windspeed     12.125325    15.625589    34.000021  
casual       717.000000  1096.500000  3410.000000  
registered  3664.500000  4783.250000  6946.000000  
cnt         4548.500000  5966.000000  8714.000000

Columnas categóricas

In [5]:
df.describe(include = 'O')

dteday  season
count          730     730
unique         730       4
top     01-01-2018  autumn
freq             1     188

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     730 non-null    int64  
 1   dteday      730 non-null    object 
 2   season      730 non-null    object 
 3   yr          730 non-null    int64  
 4   mnth        730 non-null    int64  
 5   holiday     730 non-null    int64  
 6   weekday     730 non-null    int64  
 7   workingday  730 non-null    int64  
 8   weathersit  730 non-null    int64  
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64  
 14  registered  730 non-null    int64  
 15  cnt         730 non-null    int64  
dtypes: float64(4), int64(10), object(2)
memory usage: 97.0+ KB


In [7]:
df.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [8]:
df.shape

(730, 16)

In [9]:
df.duplicated().sum()

0

In [10]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

tenemos que cambiar estación del año. Mirar working day y holiday. Hay un calendario de festivos para Washington

---

In [11]:
df.season.unique()

array(['spring', 'summer', 'autumn', 'winter'], dtype=object)

In [12]:
df_spring= df[df['season']== 'spring']
df_summer= df[df['season']== 'summer']
df_autumn= df[df['season']== 'autumn']
df_winter= df[df['season']== 'winter']

In [13]:
df_spring.mnth.unique()

array([ 1,  2,  3, 12])

In [14]:
df.loc[ :,['mnth','season']]

mnth  season
0       1  spring
1       1  spring
2       1  spring
3       1  spring
4       1  spring
..    ...     ...
725    12  spring
726    12  spring
727    12  spring
728    12  spring
729    12  spring

[730 rows x 2 columns]

In [15]:
df_summer.mnth.unique()

array([3, 4, 5, 6])

In [16]:
df_autumn.mnth.unique()

array([6, 7, 8, 9])

In [17]:
df_winter.mnth.unique()

array([ 9, 10, 11, 12])

Convertimos la columna 'dteday' a formato datetime

In [18]:
df['date']=df.dteday.apply(pd.to_datetime)

/tmp/ipykernel_2804/1936940852.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['date']=df.dteday.apply(pd.to_datetime)


In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 0 to 729
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   instant     730 non-null    int64         
 1   dteday      730 non-null    object        
 2   season      730 non-null    object        
 3   yr          730 non-null    int64         
 4   mnth        730 non-null    int64         
 5   holiday     730 non-null    int64         
 6   weekday     730 non-null    int64         
 7   workingday  730 non-null    int64         
 8   weathersit  730 non-null    int64         
 9   temp        730 non-null    float64       
 10  atemp       730 non-null    float64       
 11  hum         730 non-null    float64       
 12  windspeed   730 non-null    float64       
 13  casual      730 non-null    int64         
 14  registered  730 non-null    int64         
 15  cnt         730 non-null    int64         
 16  date        730 non-null  

Vamos a hacer una funcion para recategorizar season correctamente

In [20]:
Y= 2018
estaciones1 = [('invierno', date(Y,  1,  1),  date(Y,  3, 20)),
              ('primavera', date(Y,  3, 21),  date(Y,  6, 20)),
              ('verano', date(Y,  6, 21),  date(Y,  9, 22)),
              ('otoño', date(Y,  9, 23),  date(Y, 12, 20)),
              ('invierno', date(Y, 12, 21),  date(Y, 12, 31))]

def get_season(fecha):

    for estacion, inicio, fin in estaciones1:
      if inicio <= fecha <= fin:
        return estacion        

In [21]:
df['season_2018']= df.date.apply(get_season)

/tmp/ipykernel_2804/1168030504.py:11: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if inicio <= fecha <= fin:


In [22]:
Y=2019
estaciones2 = [('invierno', date(Y,  1,  1),  date(Y,  3, 20)),
              ('primavera', date(Y,  3, 21),  date(Y,  6, 20)),
              ('verano', date(Y,  6, 21),  date(Y,  9, 22)),
              ('otoño', date(Y,  9, 23),  date(Y, 12, 20)),
              ('invierno', date(Y, 12, 21),  date(Y, 12, 31))]


def get_season(fecha):

    for estacion, inicio, fin in estaciones2:
      if inicio <= fecha <= fin:
        return estacion


In [23]:
df['season_2019']= df.date.apply(get_season)

/tmp/ipykernel_2804/2973352361.py:12: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if inicio <= fecha <= fin:


In [24]:
df.sample(10)

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
47        48  17-02-2018  spring   0     2        0        4           1   
265      266  23-09-2018  winter   0     9        0        5           1   
616      617  09-09-2019  autumn   1     9        0        0           0   
87        88  29-03-2018  summer   0     3        0        2           1   
182      183  02-07-2018  autumn   0     7        0        6           0   
369      370  05-01-2019  spring   1     1        0        4           1   
579      580  03-08-2019  autumn   1     8        0        5           1   
231      232  20-08-2018  autumn   0     8        0        6           0   
664      665  27-10-2019  winter   1    10        0        6           0   
684      685  16-11-2019  winter   1    11        0        5           1   

     weathersit       temp     atemp      hum  windspeed  casual  registered  \
47            1  17.869153  21.43290  50.5000  15.416968     259        2216   
265           2  24.975847  26.10625  97.2500   5.250569     258        2137   
616           1  25.010000  28.94625  54.7500  15.041232    2570        5657   
87            1  12.402500  14.64540  31.4167  15.208732     317        2108   
182           1  30.271653  33.36540  44.4583   7.709154    2204        2915   
369           1  10.899153  13.92060  52.4167   8.709129     140        3132   
579           2  31.399153  36.14335  64.2500  14.458064    1328        5847   
231           1  28.597500  32.44980  67.4167   6.999289    1914        3277   
664           2  21.730000  25.75665  72.0000  15.791364    2643        5209   
684           1  14.145000  17.36020  52.4583  11.458675     484        5214   

      cnt       date season_2018 season_2019  
47   2475 2018-02-17    invierno        None  
265  2395 2018-09-23       otoño        None  
616  8227 2019-09-09        None      verano  
87   2425 2018-03-29   primavera        None  
182  5119 2018-02-07    invierno        None  
369  3272 2019-05-01        None   primavera  
579  7175 2019-03-08        None    invierno  
231  5191 2018-08-20      verano        None  
664  7852 2019-10-27        None       otoño  
684  5698 2019-11-16        None       otoño

In [25]:
df['season_concat']=df[['season_2018','season_2019']].apply(lambda x:''.join(x.dropna().astype(str)),axis=1)


In [26]:
df.date.dtype

dtype('<M8[ns]')

In [27]:
def dia_semana(col):
    return col.isoweekday()

In [28]:
df['dia_semana']= df['date'].apply(dia_semana)

In [29]:
df.dteday.dtypes

dtype('O')

In [30]:
#festivos 2018

usa_holidays = holidays.US()
for i in holidays.US(years=2018).items():
    print(i)

(datetime.date(2018, 1, 1), "New Year's Day")
(datetime.date(2018, 1, 15), 'Martin Luther King Jr. Day')
(datetime.date(2018, 2, 19), "Washington's Birthday")
(datetime.date(2018, 5, 28), 'Memorial Day')
(datetime.date(2018, 7, 4), 'Independence Day')
(datetime.date(2018, 9, 3), 'Labor Day')
(datetime.date(2018, 10, 8), 'Columbus Day')
(datetime.date(2018, 11, 11), 'Veterans Day')
(datetime.date(2018, 11, 12), 'Veterans Day (Observed)')
(datetime.date(2018, 11, 22), 'Thanksgiving')
(datetime.date(2018, 12, 25), 'Christmas Day')


In [31]:
# festivos 2019
usa_holidays = holidays.US()
for i in holidays.US(years=2019).items():
    print(i)

(datetime.date(2019, 1, 1), "New Year's Day")
(datetime.date(2019, 1, 21), 'Martin Luther King Jr. Day')
(datetime.date(2019, 2, 18), "Washington's Birthday")
(datetime.date(2019, 5, 27), 'Memorial Day')
(datetime.date(2019, 7, 4), 'Independence Day')
(datetime.date(2019, 9, 2), 'Labor Day')
(datetime.date(2019, 10, 14), 'Columbus Day')
(datetime.date(2019, 11, 11), 'Veterans Day')
(datetime.date(2019, 11, 28), 'Thanksgiving')
(datetime.date(2019, 12, 25), 'Christmas Day')


In [32]:
festivos_2018 =[]
usa_holidays = holidays.US()
for i in holidays.US(years=2018).items():
    festivos_2018.append(i[0])

In [33]:
festivos_2018

[datetime.date(2018, 1, 1),
 datetime.date(2018, 1, 15),
 datetime.date(2018, 2, 19),
 datetime.date(2018, 5, 28),
 datetime.date(2018, 7, 4),
 datetime.date(2018, 9, 3),
 datetime.date(2018, 10, 8),
 datetime.date(2018, 11, 11),
 datetime.date(2018, 11, 12),
 datetime.date(2018, 11, 22),
 datetime.date(2018, 12, 25)]

In [34]:
type(festivos_2018[0])

datetime.date

Funcion para localizar festivos

In [35]:
def festivos(año):
    lista_festivos = []
    usa_holidays = df.dteday
    for i in holidays.US(years=año).items():
        lista_festivos.append(i[0])
    return lista_festivos

In [38]:
festivos_19=festivos(2019)

In [39]:
festivos_19

[datetime.date(2019, 1, 1),
 datetime.date(2019, 1, 21),
 datetime.date(2019, 2, 18),
 datetime.date(2019, 5, 27),
 datetime.date(2019, 7, 4),
 datetime.date(2019, 9, 2),
 datetime.date(2019, 10, 14),
 datetime.date(2019, 11, 11),
 datetime.date(2019, 11, 28),
 datetime.date(2019, 12, 25)]

Sobreescribir las columnas con sus valores correctos

In [59]:
df.weekday = df. dia_semana

In [60]:
df.season =df.season_concat 

In [57]:
df.dteday=df.date

In [56]:
df['mnth'] =df['dteday'].dt.month

Pruebas para la columna festivos 

In [58]:
df["dteday"][0][6:]

TypeError: 'Timestamp' object is not subscriptable

In [53]:
def festivo_ok(col): #última función que hicimos, no funcionó al hacer el apply
    i=0
    if holidays.US(years=col[i][6:]):
        i =+ 1
        return 'festivo'
      

In [54]:
df['festivo_ok']=df['dteday'].apply(festivo_ok)

TypeError: 'Timestamp' object is not subscriptable

In [ ]:
df.festivo_ok.unique()

In [51]:
df['festivos'].unique()

KeyError: 'festivos'

In [49]:
df.head(2)

instant     dteday    season  yr  mnth  holiday  weekday  workingday  \
0        1 2018-01-01  invierno   0     1        0        1           0   
1        2 2018-02-01  invierno   0     1        0        4           0   

   weathersit       temp  ...      hum  windspeed  casual  registered  cnt  \
0           2  14.110847  ...  80.5833  10.749882     331         654  985   
1           2  14.902598  ...  69.6087  16.652113     131         670  801   

        date season_2018 season_2019 season_concat dia_semana  
0 2018-01-01    invierno        None      invierno          1  
1 2018-02-01    invierno        None      invierno          4  

[2 rows x 21 columns]