## Predicción del modelo. 

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import pickle

In [24]:
df = pd.read_csv('../datos/cnt/11-cnt-cod_est.csv',index_col =0)
df.head(2)

atemp       hum  windspeed  season  yr  mnth  holiday  weekday  \
0 -0.456399  0.855582  -0.208909       0   0     0        0        0   
1 -0.492863  0.332722   0.687550       0   0     0        2        0   

   weathersit  cnt  
0           1  985  
1           1  801

# Predicciones de alquileres de un año y otro

In [25]:
usuario = {'atemp':15.7, 'hum':78, 'windspeed':10.9,'season':'primavera','yr':0,'mnth':7,'holiday':'festivo','weekday':7,'weathersit':1}

In [26]:
usuario2 = {'atemp':15.7, 'hum':78, 'windspeed':10.9,'season':'primavera','yr':1,'mnth':7,'holiday':'festivo','weekday':7,'weathersit':1}

## Función para predecir la variable respuesta CNT

In [27]:
def prediccion_cnt(prediccion):

    df_usuario = pd.DataFrame(prediccion,index =[0])

    df_usuario_numericas = df_usuario[['atemp','hum','windspeed']]
    
    # cargar estandarizacion

    with open('11_robust_cnt.pkl','rb') as f:
        robust = pickle.load(f)
    
    df_usuario_estan = pd.DataFrame(robust.transform(df_usuario_numericas),columns = df_usuario_numericas.columns)

    # encoding

    mapa_season = {'invierno':0, 'primavera':1, 'otoño':1, 'verano':2} 
    mapa_holiday = {'festivo':0, 'no festivo':2} 
    mapa_weekday = {7:1, 1:0, 2:0, 3:0, 4:2, 5:1, 6:1}
    mapa_weather = {3:0, 2:1, 1:2}
    mapa_mes = {1:0, 2:0, 3:1, 4:2, 5:3, 6:3, 7:3, 8:3, 9:3, 10:3, 11:2, 12:1}

    df_usuario['season']= df_usuario['season'].map(mapa_season)
    df_usuario['holiday']= df_usuario['holiday'].map(mapa_holiday)
    df_usuario['weekday']= df_usuario['weekday'].map(mapa_weekday)
    df_usuario['weathersit']= df_usuario['weathersit'].map(mapa_weather)
    df_usuario['mnth']= df_usuario['mnth'].map(mapa_mes)
    
    with open('../datos/cnt/12-cnt-random.pkl','rb') as f:
        bosque = pickle.load(f)

    return bosque.predict(df_usuario), df_usuario 
    


In [28]:
usuario_prediccion_cnt = prediccion_cnt(usuario)

In [29]:
usuario_prediccion_cnt

(array([3906.96475781]),
    atemp  hum  windspeed  season  yr  mnth  holiday  weekday  weathersit
 0   15.7   78       10.9       1   0     3        0        1           2)

In [30]:
usuario_prediccion2_cnt = prediccion_cnt(usuario2)

In [31]:
usuario_prediccion2_cnt

(array([5555.06277913]),
    atemp  hum  windspeed  season  yr  mnth  holiday  weekday  weathersit
 0   15.7   78       10.9       1   1     3        0        1           2)

---

## Función para predecir la variable respuesta Casual

In [32]:
def prediccion_casual(prediccion):

    df_usuario = pd.DataFrame(prediccion,index =[0])

    df_usuario_numericas = df_usuario[['atemp','hum','windspeed']]
    
    # cargar estandarizacion

    with open('../datos/casual/15_robust_casual.pkl','rb') as f:
        robust = pickle.load(f)
    
    df_usuario_estan = pd.DataFrame(robust.transform(df_usuario_numericas),columns = df_usuario_numericas.columns)

    # encoding

    mapa_season = {'invierno':0, 'otoño':1, 'primavera':2, 'verano':3} 
    mapa_holiday = {'festivo':0, 'no festivo':2} 
    mapa_weekday = { 1:3, 2:1, 3:0, 4:0, 5:0, 6:0, 7:2}
    mapa_weather = {3:0, 2:1, 1:2}
    mapa_mes = {1:0, 2:0, 3:1, 4:2, 5:3, 6:3, 7:3, 8:3, 9:3, 10:2, 11:1, 12:0}

    df_usuario['season']= df_usuario['season'].map(mapa_season)
    df_usuario['holiday']= df_usuario['holiday'].map(mapa_holiday)
    df_usuario['weekday']= df_usuario['weekday'].map(mapa_weekday)
    df_usuario['weathersit']= df_usuario['weathersit'].map(mapa_weather)
    df_usuario['mnth']= df_usuario['mnth'].map(mapa_mes)
    
    with open('../datos/casual/16_random_casual.pkl','rb') as f:
        bosque = pickle.load(f)

    return bosque.predict(df_usuario), df_usuario 

In [33]:
usuario_prediccion_casual = prediccion_casual(usuario)

In [34]:
usuario_prediccion_casual

(array([1140.4832197]),
    atemp  hum  windspeed  season  yr  mnth  holiday  weekday  weathersit
 0   15.7   78       10.9       2   0     3        0        2           2)

In [35]:
usuario_prediccion2_casual = prediccion_casual(usuario2)

In [36]:
usuario_prediccion2_casual

(array([962.35486925]),
    atemp  hum  windspeed  season  yr  mnth  holiday  weekday  weathersit
 0   15.7   78       10.9       2   1     3        0        2           2)

### Funcion para predecir la variable registered

In [37]:
def prediccion_registered(prediccion):

    df_usuario = pd.DataFrame(prediccion,index =[0])

    df_usuario_numericas = df_usuario[['atemp','hum','windspeed']]
    
    # cargar estandarizacion

    with open('../datos/registrados/06_robust_registered.pkl','rb') as f:
        robust = pickle.load(f)
    
    df_usuario_estan = pd.DataFrame(robust.transform(df_usuario_numericas),columns = df_usuario_numericas.columns)

    # encoding

    mapa_season = {'invierno':0, 'primavera':1, 'otoño':1, 'verano':2} 
    mapa_holiday = {'festivo':0, 'no festivo':1} 
    mapa_weekday = {7:0, 1:0, 2:1, 3:2, 4:3, 5:3, 6:3}
    mapa_weather = {3: 0, 2:1, 1:2}
    mapa_mes = {1: 0, 2:0, 3:1, 4:1, 5:2, 6:2, 7:2, 8:2, 9:2, 10:2, 11:1, 12:1}

    df_usuario['season']= df_usuario['season'].map(mapa_season)
    df_usuario['holiday']= df_usuario['holiday'].map(mapa_holiday)
    df_usuario['weekday']= df_usuario['weekday'].map(mapa_weekday)
    df_usuario['weathersit']= df_usuario['weathersit'].map(mapa_weather)
    df_usuario['mnth']= df_usuario['mnth'].map(mapa_mes)
    
    with open('../datos/registrados/07_random_casual.pkl','rb') as f:
        bosque = pickle.load(f)

    return bosque.predict(df_usuario), df_usuario 

In [38]:
usuario_prediccion_registered = prediccion_registered(usuario)

In [39]:
usuario_prediccion_registered

(array([2836.44143225]),
    atemp  hum  windspeed  season  yr  mnth  holiday  weekday  weathersit
 0   15.7   78       10.9       1   0     2        0        0           2)

In [40]:
usuario_prediccion2_registered = prediccion_registered(usuario2)

In [41]:
usuario_prediccion2_registered

(array([4115.59661803]),
    atemp  hum  windspeed  season  yr  mnth  holiday  weekday  weathersit
 0   15.7   78       10.9       1   1     2        0        0           2)