Abrimo el archivo

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date, datetime


In [3]:
df = pd.read_csv('../datos/bikes.csv',index_col = 0)

In [4]:
df.head(2)

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  01-01-2018  spring   0     1        0        6           0   
1        2  02-01-2018  spring   0     1        0        0           0   

   weathersit       temp     atemp      hum  windspeed  casual  registered  \
0           2  14.110847  18.18125  80.5833  10.749882     331         654   
1           2  14.902598  17.68695  69.6087  16.652113     131         670   

   cnt  
0  985  
1  801

columnas numéricas

In [5]:
df.describe().T

count         mean          std        min          25%  \
instant     730.0   365.500000   210.877136   1.000000   183.250000   
yr          730.0     0.500000     0.500343   0.000000     0.000000   
mnth        730.0     6.526027     3.450215   1.000000     4.000000   
holiday     730.0     0.028767     0.167266   0.000000     0.000000   
weekday     730.0     2.997260     2.006161   0.000000     1.000000   
workingday  730.0     0.683562     0.465405   0.000000     0.000000   
weathersit  730.0     1.394521     0.544807   1.000000     1.000000   
temp        730.0    20.319259     7.506729   2.424346    13.811885   
atemp       730.0    23.726322     8.150308   3.953480    16.889713   
hum         730.0    62.765175    14.237589   0.000000    52.000000   
windspeed   730.0    12.763620     5.195841   1.500244     9.041650   
casual      730.0   849.249315   686.479875   2.000000   316.250000   
registered  730.0  3658.757534  1559.758728  20.000000  2502.250000   
cnt         730.0  4508.006849  1936.011647  22.000000  3169.750000   

                    50%          75%          max  
instant      365.500000   547.750000   730.000000  
yr             0.500000     1.000000     1.000000  
mnth           7.000000    10.000000    12.000000  
holiday        0.000000     0.000000     1.000000  
weekday        3.000000     5.000000     6.000000  
workingday     1.000000     1.000000     1.000000  
weathersit     1.000000     2.000000     3.000000  
temp          20.465826    26.880615    35.328347  
atemp         24.368225    30.445775    42.044800  
hum           62.625000    72.989575    97.250000  
windspeed     12.125325    15.625589    34.000021  
casual       717.000000  1096.500000  3410.000000  
registered  3664.500000  4783.250000  6946.000000  
cnt         4548.500000  5966.000000  8714.000000

Columnas categóricas

In [6]:
df.describe(include = 'O')

dteday  season
count          730     730
unique         730       4
top     01-01-2018  autumn
freq             1     188

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 0 to 729
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     730 non-null    int64  
 1   dteday      730 non-null    object 
 2   season      730 non-null    object 
 3   yr          730 non-null    int64  
 4   mnth        730 non-null    int64  
 5   holiday     730 non-null    int64  
 6   weekday     730 non-null    int64  
 7   workingday  730 non-null    int64  
 8   weathersit  730 non-null    int64  
 9   temp        730 non-null    float64
 10  atemp       730 non-null    float64
 11  hum         730 non-null    float64
 12  windspeed   730 non-null    float64
 13  casual      730 non-null    int64  
 14  registered  730 non-null    int64  
 15  cnt         730 non-null    int64  
dtypes: float64(4), int64(10), object(2)
memory usage: 97.0+ KB


In [8]:
df.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [9]:
df.shape

(730, 16)

In [10]:
df.duplicated().sum()

0

In [11]:
df.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

tenemos que cambiar estación del año. Mirar working day y holiday. Hay un calendario de festivos para Washington

---

In [12]:
df.season.unique()

array(['spring', 'summer', 'autumn', 'winter'], dtype=object)

In [13]:
df_spring= df[df['season']== 'spring']
df_summer= df[df['season']== 'summer']
df_autumn= df[df['season']== 'autumn']
df_winter= df[df['season']== 'winter']

In [14]:
df_spring.mnth.unique()

array([ 1,  2,  3, 12])

In [15]:
df.loc[ :,['mnth','season']]

mnth  season
0       1  spring
1       1  spring
2       1  spring
3       1  spring
4       1  spring
..    ...     ...
725    12  spring
726    12  spring
727    12  spring
728    12  spring
729    12  spring

[730 rows x 2 columns]

In [16]:
df_summer.mnth.unique()

array([3, 4, 5, 6])

In [17]:
df_autumn.mnth.unique()

array([6, 7, 8, 9])

In [18]:
df_winter.mnth.unique()

array([ 9, 10, 11, 12])

Convertimos la columna 'dteday' a formato datetime

In [19]:
df['date']=df.dteday.apply(pd.to_datetime)

/var/folders/db/hp0l5_js4yv8br5y2tc3frpm0000gn/T/ipykernel_15013/1936940852.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df['date']=df.dteday.apply(pd.to_datetime)


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 730 entries, 0 to 729
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   instant     730 non-null    int64         
 1   dteday      730 non-null    object        
 2   season      730 non-null    object        
 3   yr          730 non-null    int64         
 4   mnth        730 non-null    int64         
 5   holiday     730 non-null    int64         
 6   weekday     730 non-null    int64         
 7   workingday  730 non-null    int64         
 8   weathersit  730 non-null    int64         
 9   temp        730 non-null    float64       
 10  atemp       730 non-null    float64       
 11  hum         730 non-null    float64       
 12  windspeed   730 non-null    float64       
 13  casual      730 non-null    int64         
 14  registered  730 non-null    int64         
 15  cnt         730 non-null    int64         
 16  date        730 non-null  

Vamos a hacer una funcion para recategorizar season correctamente

In [41]:
Y= 2018
estaciones1 = [('invierno', date(Y,  1,  1),  date(Y,  3, 20)),
              ('primavera', date(Y,  3, 21),  date(Y,  6, 20)),
              ('verano', date(Y,  6, 21),  date(Y,  9, 22)),
              ('otoño', date(Y,  9, 23),  date(Y, 12, 20)),
              ('invierno', date(Y, 12, 21),  date(Y, 12, 31))]

def get_season(fecha):

    for estacion, inicio, fin in estaciones1:
      if inicio <= fecha <= fin:
        return estacion        

In [42]:
df['season_2018']= df.date.apply(get_season)

/var/folders/db/hp0l5_js4yv8br5y2tc3frpm0000gn/T/ipykernel_15013/811699467.py:11: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if inicio <= fecha <= fin:


In [44]:
Y=2019
estaciones2 = [('invierno', date(Y,  1,  1),  date(Y,  3, 20)),
              ('primavera', date(Y,  3, 21),  date(Y,  6, 20)),
              ('verano', date(Y,  6, 21),  date(Y,  9, 22)),
              ('otoño', date(Y,  9, 23),  date(Y, 12, 20)),
              ('invierno', date(Y, 12, 21),  date(Y, 12, 31))]


def get_season(fecha):

    for estacion, inicio, fin in estaciones2:
      if inicio <= fecha <= fin:
        return estacion


In [45]:
df['season_2019']= df.date.apply(get_season)

/var/folders/db/hp0l5_js4yv8br5y2tc3frpm0000gn/T/ipykernel_15013/2489727053.py:12: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  if inicio <= fecha <= fin:


In [48]:
df.sample(10)

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
648      649  11-10-2019  winter   1    10        0        4           1   
98        99  09-04-2018  summer   0     4        0        6           0   
421      422  26-02-2019  spring   1     2        0        0           0   
563      564  18-07-2019  autumn   1     7        0        3           1   
497      498  13-05-2019  summer   1     5        0        0           0   
128      129  09-05-2018  summer   0     5        0        1           1   
100      101  11-04-2018  summer   0     4        0        1           1   
612      613  05-09-2019  autumn   1     9        0        3           1   
687      688  19-11-2019  winter   1    11        0        1           1   
197      198  17-07-2018  autumn   0     7        0        0           0   

     weathersit       temp     atemp      hum  windspeed  casual  registered  \
648           1  17.835000  21.55835  46.3333  12.166932     834        6736   
98            2  14.042500  17.07645  87.7500   8.916561     879        1576   
421           1  11.445847  13.41540  41.0000  13.750343     515        2874   
563           1  32.526653  37.27915  57.7083   9.208614     799        4914   
497           1  25.112500  29.26190  57.6250  15.082839    2172        3946   
128           1  21.832500  26.26230  58.8750  11.792000     664        3698   
100           2  24.421732  28.26085  71.6956  21.739758     855        2493   
612           1  30.203347  35.44915  74.1250  12.583136     832        6280   
687           2  15.614153  18.78105  62.3333  15.749489     449        5050   
197           1  29.485847  33.49165  60.4167  16.417211    2006        3296   

      cnt       date season_2018 season_2019     season_ok  
648  7570 2019-11-10        None       otoño           NaN  
98   2455 2018-09-04      verano        None  veranoverano  
421  3389 2019-02-26        None    invierno           NaN  
563  5713 2019-07-18        None      verano           NaN  
497  6118 2019-05-13        None   primavera           NaN  
128  4362 2018-09-05      verano        None  veranoverano  
100  3348 2018-11-04       otoño        None    otoñootoño  
612  7112 2019-05-09        None   primavera           NaN  
687  5499 2019-11-19        None       otoño           NaN  
197  5302 2018-07-17      verano        None  veranoverano